### PR TITLE
Add web docker

### PR DESCRIPTION
**Pull request by dchassin**
The PR address how to run the web app on docker.  The approach uses `docker-compose` by adding the required configuration files for the web app and the mysql server.

# Issues
* When `docker-compose up` is run, the app reports the IP address and port to use to connect, but the server does not respond.

# Files changed
- [x] Add matter related to using docker in `README.md`
- [x] Add `web/docker-compose.yml` to configure the docker system
- [x] Add `web/db/init.sql` to initialization MySQL server
- [x] Add `web/web/Dockerfile` to setup flask app
- [x] Add `web/web/setup.sh` to start the flask app
- [x] Add `web/web/requirements.txt` because `docker-compose` cannot reference the one in the `web` folder itself.

# Documentation changes
None

# Testing and validation notes
None

### CODE REVIEW

**Comment by dchassin** [comment]
@jongoncalves maybe you can advise me on what’s missing in this PR so I can fix it tomorrow.

**Comment by jongoncalves** [comment]
I'm not sure I'll have much time today, but Ill take a look soon

**Comment by jongoncalves** [comment]
I haven't had time to look into this, so I think we should close it. FWIW, you don't need anaconda to run the project. You can use anything that exposes python 3.x to you. e.g. miniconda, homebrew or even just docker (but w/o worrying about composing the DB).

**Comment by dchassin** [comment]
Wasn't the point of the exercise to bring up the system in docker?  If that's already working elsewhere/otherwise, then I see no point in keeping this PR open or resolving the remaining issue.  If there isn't a way to bring it up in docker, then this PR may be useful to anyone who needs to use docker and it should be completed.

**Comment by jongoncalves** [comment]
> Wasn't the point of the exercise to bring up the system in docker? If that's already working elsewhere/otherwise, then I see no point in keeping this PR open or resolving the remaining issue. If there isn't a way to bring it up in docker, then this PR may be useful to anyone who needs to use docker and it should be completed.

Wholeheartedly agree - the point of this IS to add docker support. Which should be easily do-able. However, right now this is very low on my priority list. I guess my point is that if there's no movement on the PR, maybe we can close it and re-engage when we need to. 

Everything works fine w/o docker right now so I figured we can focus on other, higher value areas.

**Comment by dchassin** [comment]
Ok. Closing if/until need to reopen arises.

**Pull request closed without merging**
