### PR TITLE
Simulation model

### PR DESCRIPTION
**Pull request by malikmayank**

### CODE REVIEW

**Comment by jongoncalves** [comment]
Was the `.gitignore` change accidental? Seems like we shouldn't add `.pyc`s nor the `.DS_Store` files into the repo.

**Comment by dchassin** [comment]
> Was the `.gitignore` change accidental? Seems like we shouldn't add `.pyc`s nor the `.DS_Store` files into the repo.

I added those to `.gitignore` because those files were present on the repo.  We shouldn't be uploading, but we did.

**Comment by jongoncalves** [comment]
Just wanted to follow up on the state of this PR. Seems like at a minimum we should close it, merge master into it and re-open. It's been very long lived so I'm wondering what its status is.

**Comment by jongoncalves** [comment]
Closing this out since it's stale. Feel free to re-open once updated.

**Pull request closed without merging**
