### PR TITLE
Add use-case documentation

### PR DESCRIPTION
**Pull request by dchassin**
This PR adds a HowTo Jupyter notebook to explain how use cases are documented.

### CODE REVIEW

**Comment by jongoncalves** [comment]
Wondering what the state of this PR is? Should we merge it, close it, does it need more work?

**Comment by dchassin** [comment]
I believe Claudio and Lynne need to transfer their documentation to these files still. Let me find out where they are and see whether we can do that now.

**Comment by dchassin** [comment]
Lynne says the docs should be done next week.

**Comment by jongoncalves** [comment]
@dchassin any movement on this or can we close it out?

**Comment by jongoncalves** [comment]
Sorry, accidentally hit close with comment instead of just comment. Feel free to re-open if still relevant

**Pull request closed without merging**
